{{- if .Values.global.imagePullSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-docker-regcred-secret
type: kubernetes.io/dockerconfigjson
data:
  {{- $auth := printf "%s:%s" .Values.dockerRegcred.username .Values.dockerRegcred.password | b64enc }}
  .dockerconfigjson: |
    {{- printf "{\"auths\":{\"https://index.docker.io/v1/\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}"
      .Values.dockerRegcred.username
      .Values.dockerRegcred.password
      .Values.dockerRegcred.email
      $auth | b64enc | nindent 6 }}
{{- end }}