{{- if hasKey .Values "route53creds" }}
{{- if hasKey .Values.route53creds "tlsPassword" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-route53-creds-secret
data:
  tls-password: {{ .Values.route53creds.tlsPassword | b64enc }}
{{- end }}
{{- end }}