{{- if hasKey .Values "gateway" }}
{{- if and (hasKey .Values.gateway "commonName") (hasKey .Values.gateway "dnsNames") }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-letsencrypt-gateway-certificate
spec:
  secretName: {{ .Release.Name }}-letsencrypt-gateway-secret
  {{- $dict := dict "Values" .Values.gateway "Release" .Release }}
  {{- include "myk8schart.certificateSpec" $dict | nindent 2 }}
{{- end }}
{{- end }}